### ISSUE TITLE
Support for whole organisation

### ISSUE THREAD

**Issue by bastelfreak** [vegasbrianc/github-monitoring#2]
Hi @vegasbrianc, thanks for the great tutorial!

It is working like a charm. I'm one of the maintainer of https://github.com/voxpupuli. Displaying a single repo, or a few, is pretty easy with your template. I would like to see some accumulated value. Like open Issues/PR/Stars for the whole org. It is probably easy to add up all values for an organisation?

Also do you think it is possible to get all the graphs you have right now generated for each repository? Maybe one dashboard for each? Creating them by hand takes a huge amount of time since we have more than 100 repos.

**Comment by vegasbrianc** [comment]
Hi @bastelfreak I'm happy you are finding the project useful. I used the https://github.com/infinityworksltd/github-exporter to grab the metrics from GitHub. If you edit the `docker-compose.yml` file go to the metrics section. Replace REPOS with ORGS you will see all Repos. This will show all Repos in the Org. You can then easily do some Top 10 queries etc.

      metrics:
    tty: true
    stdin_open: true
    expose:
      - 9171
    ports:
      - 9171:9171
    image: infinityworks/github-exporter:latest
    environment:
       - ORGS=docker

I also uploaded a new dashboard that totals all GitHub stars for and an example top 5 query. Just import the JSON into Grafana and it should work if your data source is named prometheu. Otherwise, update the query. - https://github.com/vegasbrianc/github-monitoring/blob/master/Grafana-Org-Stats.json

Let me know if this works for you or not.

Cheers.
